### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by hinkel** [Crashpilot1000/TestCode3#5]
https://github.com/cleanflight/cleanflight/issues/281#issuecomment-68463897

**Comment by hinkel** [comment]
no bug in testcode 3

**Comment by Crashpilot1000** [comment]
Happy new year Hinkel!
Thanks for checking the code! Couple of months ago I adjusted the Horizon mode a little more to my flying habits. So I added a bit more precision in the transition calculation and made the transition to gyro only a bit earlier on the sticks so the coper "comes better around"....
Cheers Rob

**Comment by hinkel** [comment]
Frohes Neues Jahr Roberto !
Your code is still the best ! thank you for that !
MfG hinkel
